# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#top-level-configuration
version: latest
tutorial: false

logging:
  level: INFO
  format: '%(levelname)s:%(name)s:%(message)s'

remote:
  ssh: ""
  path: ""

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  prefix: "transfer_eur"
  name:
    - endogenous
    - frozen_H2_29
    - no_co2_network
    - onshore_seq_endo
    - pcipmi
    - seq_50
  scenarios:
    enable: true
    file: config/co2.scenarios.yaml
  disable_progressbar: false
  shared_resources:
    policy: false
    exclude: []
  shared_cutouts: true
  use_shadow_directory: true # Set to false if problems regarding missing directories occur

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: myopic

# Solve two-step operations
solve_operations:
  resample_temporal_resolution: false
  columns:
    - ops_industry_demand
    - ops_sequ_potential
    - ops_meoh_import
  definitions:
    ops_industry_demand:
      allow_load_shedding: 10000 # EUR/MWh
      fix_minimum_investments: true # all assets except for pipelines
      fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
      # 
      adjust_industry_demand: 1.2
      adjust_seq_limit: false
      allow_meoh_import: false
    ops_sequ_potential:
      allow_load_shedding: 10000 # EUR/MWh
      fix_minimum_investments: true # all assets except for pipelines
      fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
      # 
      adjust_industry_demand: false
      adjust_seq_limit: 90
      allow_meoh_import: false
    ops_meoh_import:
      allow_load_shedding: 10000 # EUR/MWh
      fix_minimum_investments: true # all assets except for pipelines
      fix_optimal_pipeline_capacities: true # CO2 and H2 pipelines
      # 
      adjust_industry_demand: false
      adjust_seq_limit: false
      allow_meoh_import: 200 # TWh industry + shipping = 291 TWh/a in 2040

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#scenario
# Wildcard docs in https://pypsa-eur.readthedocs.io/en/latest/wildcards.html
scenario:
  clusters:
  - adm
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2030
  - 2040
  - 2050

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries: ['AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK', 'XK']

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: enable

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#electricity
electricity:
  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, onwind, offwind-ac, offwind-dc, hydro]
  transmission_limit: v1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#transmission_projects
transmission_projects:
  enable: true
  include:
    pcipmi: false
    tyndp2020: true
    nep: true
    manual: false
  skip:
  - upgraded_lines
  - upgraded_links
  status:
    pcipmi: ['under_construction', 'in_permitting', 'confirmed', 'planned_not_yet_permitted', 'under_consideration']
    tyndp2020: ['under_construction', 'in_permitting', 'confirmed']
    nep: ['under_construction', 'in_permitting', 'confirmed']
  new_link_capacity: keep # keep or zero

carrier_networks:
  CO2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      cost_factor: 1.0
      length_factor: 1.0
      delay: 5
  H2:
    enable: true
    include:
      greenfield: true
      pcipmi: true
    extendable:
      greenfield: ['national', 'international']
      pcipmi: []
    p_nom_max: .inf
    options:
      delay: 5

pcipmi_projects:
  enable: true
  include:
    - stores_co2
    - stores_h2
  options:
    delay: 5

existing_capacities:
  grouping_years_power: [1920, 1950, 1955, 1960, 1965, 1970, 1975, 1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2020, 2025]
  grouping_years_heat: [1980, 1985, 1990, 1995, 2000, 2005, 2010, 2015, 2019] # heat grouping years >= baseyear will be ignored
  grouping_years_industry: [1995, 2000, 2005, 2010, 2015, 2020, 2025]

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#sector
sector:
  transport: true
  heating: true
  biomass: true
  industry: true
  shipping: true
  aviation: true
  agriculture: true
  fossil_fuels: true
  SMR: true
  SMR_cc: true
  regional_oil_demand: true
  regional_coal_demand: false
  regional_co2_sequestration_potential:
    enable: true
    attribute:
    - conservative estimate GAS Mt
    - conservative estimate OIL Mt
    include_onshore: false
    min_size: 3
    max_size: .inf # 25
    years_of_storage: 25
  co2_vent: true
  co2_sequestration_potential:
    2030: 40
    2040: 180
    2050: 250
  co2_sequestration_cost: 35
  co2_sequestration_lifetime: 50
  co2_spatial: true
  gas_network: false
  H2_retrofit: false
  H2_retrofit_capacity_per_CH4: 0.6
  gas_network_connectivity_upgrade: 1
  gas_distribution_grid: true
  gas_distribution_grid_cost_factor: 1.0
  biomass_spatial: true
  biomass_transport: false
  biogas_upgrading_cc: false
  ammonia: regional
  methanol:
    regional_methanol_demand: true
  endogenous_sectors:
    - steel
    - cement
    - ammonia
    - methanol
  bof_retirement_date: true
  industry_relocation: false

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  mode: administrative
  administrative:
    level: 1
    FI: 2
    'NO': 2
    AT: 0
    BA: 0
    BG: 0
    HR: 0
    HU: 0
    RO: 0
    RS: 0
    XK: 0
  administrative_options: # build_shapes
    remove_small_baltic_islands: true
    split_sardinia_sicily: true
    merge_city_states: true
  focus_weights:
    FI: 0.05
    'NO': 0.05
    PL: 0.07
    SE: 0.05
  temporal:
    resolution_elec: false
    resolution_sector: 25H # 2190seg

solving:
  mem_mb: 400000 #memory in MB; 20 GB enough for 50+B+I+H2; 100 GB for 181+B+I+H2
  memory_logging_frequency: 30 # in seconds
  runtime: 40h #runtime in humanfriendly style https://humanfriendly.readthedocs.io/en/latest/
  options:
    assign_all_duals: true
    custom_extra_functionality: ../data/custom_extra_functionality.py # Has to be set to false, otherwise the imported solve_network function will not work correctly
    noisy_costs: true
    skip_iterations: false
    max_iterations: 1
    post_discretization:
      enable: true
      link_unit_size:
        DC: 1000
        H2 pipeline: 4700
        CO2 pipeline: 1328 # pipeline diamter 70cm able to transport 1328 t/h
      link_threshold:
        DC: 0.3
        H2 pipeline: 0.05
        CO2 pipeline: 0.1
      fractional_last_unit_size: true